name: changelog
on: pull_request_target
permissions: write-all
jobs:
    amend:
        name: "Validate staged changelogs"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                ref: ${{ github.head_ref }}
                repository: ${{ github.event.pull_request.head.repo.full_name }}

            - uses: actions/setup-python@v5
              with:
                python-version: "3.13"

            - name: "Run validation script"
              env:
                GITHUB_TOKEN: ${{ github.token }}
                TARGET_SHA: ${{ github.event.pull_request.head.sha }}
                PR_TITLE: ${{ github.event.pull_request.title }}
              run: |
                git fetch origin ${{ github.base_ref }}
                ./.changes/amend --review-comment -n ${{ github.event.pull_request.number }}
